name: Daily Market Update (Hugging Face)

# Trigger workflow on schedule and manually
on:
  schedule:
    - cron: '10 16 * * *'  # 16:10 UTC = 21:40 IST
  workflow_dispatch:        # allows manual trigger

jobs:
  run-market-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Market Bot
        run: python .github/workflows/market_update_runner.py
