name: Daily Market Update Bot (Free)

on:
  schedule:
    - cron: "30 10 * * *"   # 10:30 UTC = 4:00 PM IST
  workflow_dispatch:         # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install PyTorch CPU for Hugging Face
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install huggingface_hub

      # 4️⃣ Run the bot
      - name: Run Market Update Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python .github/workflows/market_update_runner.py
