name: Daily Market Update

on:
  schedule:
    # Runs every day at 4:00 PM IST (10:30 AM UTC)
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  run-market-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install yfinance transformers torch requests

      - name: Run market update bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python .github/workflows/market_update_runner.py
