name: Daily Market Update

# Run the workflow on a schedule (5 PM IST)
on:
  schedule:
    - cron: '30 13 * * *'  # 11:30 UTC = 17:00 IST
  workflow_dispatch:      # Allows manual triggering from GitHub

jobs:
  send_market_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests pytz

      - name: Run market update script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python .github/workflows/market_update_runner.py
